#include <rfauds2/rfauds2.h>

/* Generated by an embedding step in the application build. */
extern const unsigned char rfauds2_irx[];
extern const unsigned int rfauds2_irx_size;

int play_pcm_block(const s16 *pcm, u32 frames)
{
    int result;

    result = rfauds2_init(rfauds2_irx, rfauds2_irx_size);
    if (result < 0)
        return result;

    result = rfauds2_set_latency_ms(43);
    if (result < 0)
        goto shutdown;

    result = rfauds2_set_volume(RFAUDS2_VOLUME_MAX);
    if (result < 0)
        goto shutdown;

    /* For a real stream, prebuffer several blocks before start when possible. */
    result = rfauds2_submit_s16(pcm, frames);
    if (result < 0)
        goto shutdown;

    result = rfauds2_start();
    if (result < 0)
        goto shutdown;

    /* Feed additional 48 kHz stereo S16 blocks here. */

    (void)rfauds2_stop();
    (void)rfauds2_flush();

shutdown:
    (void)rfauds2_shutdown();
    return result < 0 ? result : 0;
}
